### ISSUE TITLE
channel mismatch - ValueError

### ISSUE THREAD

**Issue by snachi2s** [ENOT-AutoDL/lpcv-2023#5]
Hi there, 
thanks for your great work on replicating the PIDNet implementation. 

I was trying to replicate the implementation for the dataset you provided(following the installation instructions exactly as provided) with the following training settings,

```
Namespace(cfg='configs/lpcv/pidnet_small_lpcv.yaml', savedir='output/lpcv/', seed=100, opts=[])
AUTO_RESUME: False
CUDNN:
  BENCHMARK: False
  DETERMINISTIC: False
  ENABLED: True
CV2_THREADS: 8
DATASET:
  DATASET: lpcv
  EXTRA_TRAIN_SET: None
  NUM_CLASSES: 14
  ROOT: data/
  TEST_SET: list/lpcv/val.lst
  TRAIN_SET: list/lpcv/train.lst
GPUS: (0,)
LOG_DIR: log
LOSS:
  BALANCE_WEIGHTS: [0.4, 1.0]
  CLASS_BALANCE: False
  OHEMKEEP: 131072
  OHEMTHRES: 0.9
  SB_WEIGHTS: 1.0
  USE_OHEM: True
MODEL:
  ALIGN_CORNERS: True
  NAME: pidnet_s
  NUM_OUTPUTS: 4
  PRETRAINED: pretrained_models/imagenet/PIDNet_S_ImageNet.pth
OUTPUT_DIR: output
PIN_MEMORY: True
PRINT_FREQ: 200
TEST:
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 2
  FLIP_TEST: False
  IMAGE_SIZE: [512, 512]
  MODEL_FILE: None
  MULTI_SCALE: False
  OUTPUT_INDEX: 1
TORCH_THREADS: 8
TRAIN:
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 2
  BEGIN_EPOCH: 0
  END_EPOCH: 400
  EXTRA_EPOCH: 0
  EXTRA_LR: 0.001
  FLIP: False
  IGNORE_LABEL: 255
  IMAGE_SIZE: [512, 512]
  LR: 0.0003
  MOMENTUM: 0.9
  MULTI_SCALE: True
  NESTEROV: False
  OPTIMIZER: radam
  RESUME: False
  SAM: False
  SAM_RHO: 0.05
  SCALE_FACTOR: 16
  SHUFFLE: True
  USE_AUX_HEADS: True
  WD: 0.00075
WORKERS: 8
```

But I was getting the following error(pasted the whole traceback for better clarity),
```
Traceback (most recent call last):
  File "/home/Desktop/lpcv-2023/training/tools/train.py", line 184, in <module>
    main()
  File "/home/Desktop/lpcv-2023/training/tools/train.py", line 112, in main
    train(
  File "/home/Desktop/lpcv-2023/training/tools/../utils/function.py", line 87, in train
    optimizer.step(closure)
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/optim/radam.py", line 94, in step
    loss = closure()
           ^^^^^^^^^
  File "/home/Desktop/lpcv-2023/training/tools/../utils/function.py", line 49, in closure
    pred = model(images)
           ^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Desktop/lpcv-2023/training/tools/../models/pidnet.py", line 173, in forward
    self.spp(self.layer5(x)),
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Desktop/lpcv-2023/training/tools/../models/model_utils.py", line 257, in forward
    scale_list.append(F.interpolate(self.scale3(x), size=[height, width],
                                    ^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/functional.py", line 2448, in batch_norm
    _verify_batch_size(input.size())
  File "/home/miniconda3/envs/pidnet/lib/python3.11/site-packages/torch/nn/functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])
```
I was trying to debug it for a while. Since it is the same dataset you used, you could help me solve this faster. 

Thanks in advance!

**Comment by AetelFinch** [comment]
fixed in #6. This is because when the last batch is reached during training, it turns out to be equal to 1. Try to set parameter TRAIN.DROP_LAST: True or increase batch_size as it is done in the original config.
